#!/bin/bash
mv .virc ~
mv .screenrc ~
mv .inputrc ~
if [ "$(grep Geri ~/.bashrc)" == "# Updated by Geri" ]; then 
	echo "The file .bashrc is already updated, nothing to do...."
else
	cat aliases >> ~/.bashrc
fi
mv .vim ~

if [ -e ~/.ssh ]; then
	cat .ssh/id_rsa.pub >> ~/.ssh/authorized_keys
else
	mv .ssh ~
	mv ~/.ssh/id_rsa.pub ~/.ssh/authorized_keys
	chmod 700 ~/.ssh
fi

if [ "$1" == "-d" ]; then
	cd 
	rm -rf UnixSettingsFiles
	if [ $? -eq 0 ]; then
		echo "Cleanup is successfull."
	else
		echo "Something went wrong with the cleanup!"
	fi
fi

# End of script. This line is only for testing
